version = 0.1

[default.build.parameters]
template_file = "aws-infrastructure/template.yaml"
parallel = true
cached = true

[default.deploy.parameters]
stack_name = "paper-trading-dev"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
resolve_s3 = true
parameter_overrides = "Environment=dev S3BucketModels=forex-ai-models"

[staging.deploy.parameters]
stack_name = "paper-trading-staging"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
resolve_s3 = true
parameter_overrides = "Environment=staging S3BucketModels=forex-ai-models"

[prod.deploy.parameters]
stack_name = "paper-trading-prod"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = true
fail_on_empty_changeset = false
resolve_s3 = true
parameter_overrides = "Environment=prod S3BucketModels=forex-ai-models"
