version = 0.1

[default.build.parameters]
template_file = "aws-infrastructure/template.yaml"
parallel = true
cached = true

[default.deploy.parameters]
stack_name = "paper-trading"
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = false
fail_on_empty_changeset = false
resolve_s3 = true
parameter_overrides = "S3BucketModels=forex-ai-models"
